.TH "boys" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boys \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBboy\fP"
.br
.ti -1c
.RI " \fBboy_geek\fP"
.br
.ti -1c
.RI " \fBboy_generous\fP"
.br
.ti -1c
.RI " \fBboy_miser\fP"
.br
.ti -1c
.RI " \fBboy_uninherited\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
