.TH "boys.boy.Boy" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boys.boy.Boy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP, \fBattr\fP, \fBbudget\fP, \fBintel\fP, \fBmin_attr\fP, \fBnature\fP)"
.br
.ti -1c
.RI "def \fBcheck_elligibility\fP (self, girl)"
.br
.ti -1c
.RI "def \fBmatch\fP (self, girl)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBattr\fP"
.br
.ti -1c
.RI "\fBbudget\fP"
.br
.ti -1c
.RI "\fBintel\fP"
.br
.ti -1c
.RI "\fBmin_attr\fP"
.br
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBnature\fP"
.br
.ti -1c
.RI "\fBpartner\fP"
.br
.ti -1c
.RI "\fBhappiness\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
BASE CLASS
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def boys\&.boy\&.Boy\&.__init__ ( self,  name,  attr,  budget,  intel,  min_attr,  nature)"

.PP
.nf
DEFAULT CONSTRUCTOR
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def boys\&.boy\&.Boy\&.check_elligibility ( self,  girl)"

.PP
.nf
CHECKS WHETHER THIS BOY IS ELIGIBLE FOR PAIRING WITH THE CURRENT GIRL
.fi
.PP
 
.SS "def boys\&.boy\&.Boy\&.match ( self,  girl)"

.PP
.nf
ASSIGNS GIRL AS THE PARTNER FOR THIS BOY
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "boys\&.boy\&.Boy\&.attr"

.SS "boys\&.boy\&.Boy\&.budget"

.SS "boys\&.boy\&.Boy\&.happiness"

.SS "boys\&.boy\&.Boy\&.intel"

.SS "boys\&.boy\&.Boy\&.min_attr"

.SS "boys\&.boy\&.Boy\&.name"

.SS "boys\&.boy\&.Boy\&.nature"

.SS "boys\&.boy\&.Boy\&.partner"

.SS "boys\&.boy\&.Boy\&.status"


.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
