.TH "couple.Couple" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
couple.Couple \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBboy\fP, \fBgirl\fP)"
.br
.ti -1c
.RI "def \fBset_happiness\fP (self)"
.br
.ti -1c
.RI "def \fBset_compatibility\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBboy\fP"
.br
.ti -1c
.RI "\fBgirl\fP"
.br
.ti -1c
.RI "\fBhappiness\fP"
.br
.ti -1c
.RI "\fBcompatibility\fP"
.br
.ti -1c
.RI "\fBgift_basket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
COUPLE CLASS
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def couple\&.Couple\&.__init__ ( self,  boy,  girl)"

.PP
.nf
DEFAULT CONSTRUCTOR
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def couple\&.Couple\&.set_compatibility ( self)"

.PP
.nf
CALCULATES COUPLE'S COMPATIBILITY
.fi
.PP
 
.SS "def couple\&.Couple\&.set_happiness ( self)"

.PP
.nf
CALCULATES COUPLE'S HAPPINESS
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "couple\&.Couple\&.boy"

.SS "couple\&.Couple\&.compatibility"

.SS "couple\&.Couple\&.gift_basket"

.SS "couple\&.Couple\&.girl"

.SS "couple\&.Couple\&.happiness"


.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
