.TH "gifts.gift.Gift" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gifts.gift.Gift \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprice\fP, \fBvalue\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprice\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
BASE CLASS
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def gifts\&.gift\&.Gift\&.__init__ ( self,  price,  value)"

.PP
.nf
DEFAULT CONSTRUCTOR
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "gifts\&.gift\&.Gift\&.price"

.SS "gifts\&.gift\&.Gift\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
