.TH "gifts.gift_utility.GiftUtility" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gifts.gift_utility.GiftUtility \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Gift\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, price, value, \fButil_value\fP, \fButil_class\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fButil_value\fP"
.br
.ti -1c
.RI "\fButil_class\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
DERIVED CLASS
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def gifts\&.gift_utility\&.GiftUtility\&.__init__ ( self,  price,  value,  util_value,  util_class)"

.PP
.nf
DEFAULT CONSTRUCTOR
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "gifts\&.gift_utility\&.GiftUtility\&.type"

.SS "gifts\&.gift_utility\&.GiftUtility\&.util_class"

.SS "gifts\&.gift_utility\&.GiftUtility\&.util_value"


.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
