.TH "girls.girl_desparate" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
girls.girl_desparate \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGirlDesparate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
DESPARATE GIRL
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
