.TH "/media/illuminatus/Study/Python Programming/Projects/PPL Assignment/girls/girl_desparate.py" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/illuminatus/Study/Python Programming/Projects/PPL Assignment/girls/girl_desparate.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgirls\&.girl_desparate\&.GirlDesparate\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgirls\&.girl_desparate\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
