.TH "girls.girl_uninherited.Girl" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
girls.girl_uninherited.Girl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP, \fBattr\fP, \fBmcost\fP, \fBintel\fP, \fBnature\fP, \fBcriteria\fP)"
.br
.ti -1c
.RI "def \fBcheck_elligibility\fP (self, boy)"
.br
.ti -1c
.RI "def \fBmatch\fP (self, boy)"
.br
.ti -1c
.RI "def \fBset_happiness\fP (self, gift_basket)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBattr\fP"
.br
.ti -1c
.RI "\fBmcost\fP"
.br
.ti -1c
.RI "\fBintel\fP"
.br
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBnature\fP"
.br
.ti -1c
.RI "\fBpartner\fP"
.br
.ti -1c
.RI "\fBhappiness\fP"
.br
.ti -1c
.RI "\fBcriteria\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
DOES NOT USE INHERITANCE
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def girls\&.girl_uninherited\&.Girl\&.__init__ ( self,  name,  attr,  mcost,  intel,  nature,  criteria)"

.SH "Member Function Documentation"
.PP 
.SS "def girls\&.girl_uninherited\&.Girl\&.check_elligibility ( self,  boy)"

.PP
.nf
CHECKS WHETHER THIS BOY IS ELIGIBLE FOR PAIRING WITH THE CURRENT GIRL
.fi
.PP
 
.SS "def girls\&.girl_uninherited\&.Girl\&.match ( self,  boy)"

.PP
.nf
ASSIGNS BOY AS THE PARTNER FOR THIS GIRL
.fi
.PP
 
.SS "def girls\&.girl_uninherited\&.Girl\&.set_happiness ( self,  gift_basket)"

.PP
.nf
CALCULATES HAPPINESS OF THIS GIRL
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "girls\&.girl_uninherited\&.Girl\&.attr"

.SS "girls\&.girl_uninherited\&.Girl\&.criteria"

.SS "girls\&.girl_uninherited\&.Girl\&.happiness"

.SS "girls\&.girl_uninherited\&.Girl\&.intel"

.SS "girls\&.girl_uninherited\&.Girl\&.mcost"

.SS "girls\&.girl_uninherited\&.Girl\&.name"

.SS "girls\&.girl_uninherited\&.Girl\&.nature"

.SS "girls\&.girl_uninherited\&.Girl\&.partner"

.SS "girls\&.girl_uninherited\&.Girl\&.status"


.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
