.TH "md__media_illuminatus__study__python__programming__projects__p_p_l__assignment__r_e_a_d_m_e" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__media_illuminatus__study__python__programming__projects__p_p_l__assignment__r_e_a_d_m_e \- ppl-assignment-coderIlluminatus 

.SS "Name : Sayantan Chatterjee"
.PP
.SS "Enrollment no\&. : IIT 2015 511"
.PP
.SS "Username : coderIlluminatus"
.PP
.SS "Language:"
.PP
.PP
.nf
1 Python 3\&.5\&.2
.fi
.PP
.PP
.SS "Platform:"
.PP
.PP
.nf
1 VS Code Version 1\&.8\&.1
.fi
.PP
.PP
.SS "Operating System:"
.PP
.PP
.nf
1 Distributor  : elementary
2 Description  : elementary OS 0\&.4 Loki
3 Release      : 0\&.4
4 Codename     : loki
.fi
.PP
.PP
.SS "Testing instructions"
.PP
.IP "\(bu" 2
Question 1: 
.PP
.nf
1 python3 question_1\&.py

.fi
.PP

.IP "\(bu" 2
Question 2: 
.PP
.nf
1 python3 question_2\&.py

.fi
.PP

.IP "\(bu" 2
All events will be logged in \fCeventlog\&.txt\fP
.IP "\(bu" 2
Algorithmic functions are present in \fC\fBalgorithms\&.py\fP\fP
.IP "\(bu" 2
Class definitions are present in \fC\fBboy_uninherited\&.py\fP\fP, \fC\fBgirl_uninherited\&.py\fP\fP, \fC\fBgift_uninherited\&.py\fP\fP and \fC\fBcouple\&.py\fP\fP
.IP "\(bu" 2
Random generator funcions are present in \fC\fBtest_utility\&.py\fP\fP
.IP "\(bu" 2
\&.csv files \fCboys\&.csv\fP, \fCgirls\&.csv\fP and \fCgifts\&.csv\fP will have randomly generated data set 
.PP

