.TH "/media/illuminatus/Study/Python Programming/Projects/PPL Assignment/question_1.py" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/illuminatus/Study/Python Programming/Projects/PPL Assignment/question_1.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBquestion_1\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
