.TH "question_2" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
question_2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcouples_list\fP = pickle\&.load(open('couple\&.p', 'rb'))"
.br
.ti -1c
.RI "\fBk\fP = randint(1, len(\fBcouples_list\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
QUESTION 2
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "question_2\&.couples_list = pickle\&.load(open('couple\&.p', 'rb'))"

.SS "question_2\&.k = randint(1, len(\fBcouples_list\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
