.TH "test_utility" 3 "Sun Feb 26 2017" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_utility \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcreate\fP (filename, datalist)"
.br
.ti -1c
.RI "def \fBrandom_generator_people\fP ()"
.br
.ti -1c
.RI "def \fBrandom_generator_gifts\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
TEST UTILITY TO RANDOMLY GENERATE csv FILES
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def test_utility\&.create ( filename,  datalist)"

.PP
.nf
CREATES csv ROWS FROM GIVEN DATA SET
.fi
.PP
 
.SS "def test_utility\&.random_generator_gifts ()"

.PP
.nf
GENERATES RANDOM LIST OF BOYS AND GIRLS
.fi
.PP
 
.SS "def test_utility\&.random_generator_people ()"

.PP
.nf
GENERATES RANDOM LIST OF BOYS AND GIRLS
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
